### ISSUE TITLE
forecasting out of test date

### ISSUE THREAD

**Issue by AZFARHAD24511** [dhopp1/nowcast_lstm#5]
Suppose the daily features span from 2010 to 2023, and the target variable covers the same time period. Now, the objective is to predict target values for the initial month of 2024. Could you please guide me on implementing this for an LSTM model, considering that the target variable is recorded monthly while the features are captured daily, thus involving mixed frequencies?

**Comment by dhopp1** [comment]
Hi, what you would need to do is set your data up like this:

date, feature_1, .... , feature_n, target
01.01.2023, x, ..., x, NA
02.01.2023, x, ..., x, NA
03.01.2023, x, ..., x, ΝΑ
...
31.01.2023, x, ..., x, y
01.02.2023, x, ..., x, NA
...
28.02.2023, x, ..., x, y

And so on. So the monthly target values go in the last day of the month, with NAs in the intervening days.

Then the `n_timesteps` parameter of the function will dictate how many days trailing to train the model on. E.g., if you set `n_timesteps` to `30`, the prediction for January 2024 will use the daily data from 02.01.2024-31.01.2024 to predict the value for January. Set it to `60` if you want it to predict based on December and January's numbers. You will have to find the best number using hyperparameter tuning and out of sample testing.

One thing to note is the library is focused on nowcasting rather than forecasting. So in your example, it will work (though I don't know how well) for predicting January 2024 as long as the `n_timesteps` is long enough to encapsulate some actual data that has been published. E.g., a value of `90` will have some published data and thus will predict something other than the mean. If it's `30`, it wouldn't start to produce non-mean predictions until we're in January.

The last thing to note is if you want predictions for January, make sure your dataframe has January's dates in it. Your data as it currently looks might only go to 20.11.2023, so it will only create predictions up until that date. Add the dates up to 31.01.2024 (with just NAs for all the values) and that will produce predictions for January as well.
